apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      retention: 2w
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
    prometheusK8s:
      retention: 2w
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
