apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
    thanosRuler:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
