---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://host.minikube.internal:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          $patch: delete
        tokenSecretRef:
          name: "nerc-shift-secrets"
          namespace: "external-secrets"
          key: "token"
