---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          serviceAccountRef:
            $patch: delete
          secretRef:
            name: "nerc-shift-secrets"
            namespace: "external-secrets"
            key: "token"
