---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - nerc-shift-secrets.yaml
  - ../../nerc-shift-1/external-secrets

patchesStrategicMerge:
  # Use this to access production vault
  # - clustersecretstore_credential_patch.yaml
  # Use this to access local dev-mode vault
  - clustersecretstore_patch.yaml
