---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - nerc-shift-secrets.yml
  - ../../nerc-shift-1/external-secrets

patchesStrategicMerge:
  - clustersecretstore_patch.yml
