---
apiVersion: v1
kind: Secret
metadata:
  name: nerc-shift-secrets
  namespace: external-secrets
stringData:
  # Fetch the token from the service user, e.g.:
  # % oc get sa -n external-secrets nerc-external-secrets -o jsonpath="{.secrets[0].name}"
  token: ADD SA TOKEN HERE
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-tls
  namespace: external-secrets
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lRWTlWNzhRWGVpV3FqTkdlcVYybzJnakFOQmdrcWhraUc5dzBCQVFzRkFEQkEKTVJVd0V3WURWUVFLRXd4Q1lXNTZZV2tnUTJ4dmRXUXhKekFsQmdOVkJBTVRIa0poYm5waGFTQkRiRzkxWkNCSApaVzVsY21GMFpXUWdVbTl2ZENCRFFUQWVGdzB5TVRFd01qRXhPREF3TlRsYUZ3MHlNakV3TWpFeE9EQXdOVGxhCk1FQXhGVEFUQmdOVkJBb1RERUpoYm5waGFTQkRiRzkxWkRFbk1DVUdBMVVFQXhNZVFtRnVlbUZwSUVOc2IzVmsKSUVkbGJtVnlZWFJsWkNCU2IyOTBJRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBbmI3bVJoTkJ1Rk15SUN2QXh3RmdtSHJKNklaTlNKK2p6TXB4cm1sUEdGZGZmM0U5cTFiSERTckdXdThQCnppd25zK29hYzhHbDY1czI3cUtoYjZzZEJIQlN3M1A4bWFVSi84aWh6MkdVanhmMnM2L2JuTnNiOGp2MWdJVUkKK1EyVkRtQnllYVVBNkZTTk8vY3ZpdlFNNEw2QU1vYnN4cWdEbmpsNXBmNzVyMU5NcHh0QmRicEtxRFFLL29kMApMREFqNzhKZHNVSHRDMVc0YzRjQ29wNk1LVVhVTDB4WUtYRHBIVlkrenpXWUNMak45dmJJTXlSell5YlZWa0k2ClNnaEV1MkZKQjNkMEt6eGN2S0h6aXh6R2J0djFhQW9HU01CZ1FXT3N5OCtVZ09nSGVkbmZDejVaSXdCZlVPRGcKOHBoQkEzelB3Zk1wdTU1QTgyMGpiUTBXL1FJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBZ1F3SFFZRApWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEClZSME9CQllFRktnQ3ljMEoxVXVtWjg3bnRLZHBJL0lWbEtPL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQi8Kelp2WXFyeHZSRVMwUEE1VzFDbnJRNnZaZG5VRzljSXdaa1VUZ0l4bVNuWlZBUjJibXdDeDlRTmU5TG52K25yRAptZzREMndkMFUyWmJHZ3h1dnRwbDBpUzN6czFubk45TUdmZnhzYUNwbUEyRGNJT1dmZ1NrT2VUdEswVDJIZ21xCkdQRG1IdXgrb3BWaFVJWkNmTi92Z0l6WWhRSTE2ZFNKVjR0eVJXYTdHWTFWTzhDMFFDb3pMek9JcUUwNHZTcVUKL2JlNTFIdzBpMERDN1ZxYmdJU3VrL1F6T2FQbEJNNmJBdzcva3lLamhGanlOK0xZY3Z3UkhvWDZTZi9mbFB4eQpQWm5LOG15NGZJZmlBSDBoSVhwT1ErdjhZK1lpb2RIaGI4VFNqekJVaTVWM2hoUU1pN2hxZkpUZzJxQjB5b09TCmJMbERxU1FZenpueUhyQ0J4ekV4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
