apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: nerc-secret-test
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aws-creds
  data:
  - secretKey: aws_secret_access_key
    remoteRef:
      key: accounts/aws
      property: AWS_SECRET_ACCESS_KEY
