{
 "title": "Virtual Machine View",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "clouds", "label": "cloud", "query": { "query": "label_values(service)" } },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(ceilometer_cpu{service=~\".+-$clouds-.+\"}, project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual Machine Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((ceilometer_cpu{project=\"$project\"}))"
    }
   ]
  },
  {
   "title": "VM CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(collectd_virt_percent, \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "{{ plugin_instance }} on {{ node }}"
    }
   ]
  },
  {
   "title": "CPU Time for Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(ceilometer_cpu{project=\"$project\"}[1m])",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(ceilometer_cpu{project=\"$project\"}) + on (resource) group_right(project) label_replace(label_replace(collectd_virt_virt_vcpu_total, \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"Node\", \"$1\", \"host\", \".+:.+:(.+)\")",
     "legendFormat": "{{ plugin_instance }}"
    }
   ]
  },
  {
   "title": "VM Memory Utilization (Allocated)",
   "type": "timeseries",
   "description": "Memory utilization of that allocated to the virtual machine.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(label_replace(label_replace(collectd_virt_memory, \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") / 1000000) / on (resource) group_left (project) ceilometer_memory_usage{project=\"$project\"}",
     "legendFormat": "{{ plugin_instance }} [{{ type_instance }}] on {{ node }}"
    }
   ]
  },
  {
   "title": "VM Disk Operations Rate",
   "type": "graph",
   "description": "Virtual machine disk operations rate (in operations/second)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_disk_ops_read_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Read {{ plugin_instance }} disk {{ type_instance }}"
    },
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_disk_ops_write_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Write {{ plugin_instance }} disk {{ type_instance }}"
    }
   ]
  },
  {
   "title": "Recent Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_type",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "labels.project_id: $project",
     "timeField": "generated"
    }
   ]
  },
  {
   "title": "VM Network Dropped Packet Rate",
   "type": "graph",
   "description": "Virtual machine network dropped packet rate (in packets-per-second)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_if_dropped_rx_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Rx {{ plugin_instance }} interface {{ type_instance }}"
    },
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_if_dropped_tx_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Tx {{ plugin_instance }} interface {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Network Error Rate",
   "type": "graph",
   "description": "Virtual machine network error rate (in packets-per-second)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_if_errors_rx_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Rx {{ plugin_instance }} interface {{ type_instance }}"
    },
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_if_errors_tx_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Tx {{ plugin_instance }} interface {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Disk Throughput Rate",
   "type": "graph",
   "description": "Virtual machine disk throughput rate (in bytes)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_disk_octets_read_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Read {{ plugin_instance }} disk {{ type_instance }}"
    },
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_disk_octets_write_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Write {{ plugin_instance }} disk {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Network Throughput Rate",
   "type": "graph",
   "description": "Virtual machine network throughput rate (in bytes)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_if_octets_rx_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Rx {{ plugin_instance }} interface {{ type_instance }}"
    },
    {
     "expr": "label_replace(label_replace(rate(collectd_virt_if_octets_tx_total[1m]), \"resource\", \"$1\", \"host\", \".+:(.+):.+\"), \"node\", \"$1\", \"host\", \".+:.+:(.+)\") + on (resource) group_left(project) (ceilometer_cpu{project=\"$project\"} * 0)",
     "legendFormat": "Tx {{ plugin_instance }} interface {{ type_instance }}"
    }
   ]
  }
 ]
}