apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/vault.vault: ""
  name: vault
  namespace: vault
spec:
  channel: beta
  installPlanApproval: Automatic
  name: vault
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
  startingCSV: vaultoperator.v0.4.10
