apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault-vault.apps.nerc-shift-0.rc.fas.harvard.edu"
      path: "secret"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "default"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "nerc-external-secrets"
            namespace: "external-secrets"
          # Optional secret field containing a Kubernetes ServiceAccount JWT
          #  used for authenticating with Vault
          secretRef:
            # Fetch the token name from the service user, e.g.:
            # % oc get sa -n external-secrets nerc-external-secrets -o jsonpath="{.secrets[0].name}"
            name: "nerc-external-secrets-token-xxxx"
            namespace: "external-secrets"
            key: "token"
