apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ../../../base/external-secrets
  - clustersecretstore.yaml

patchesStrategicMerge:
  - deployments/nerc-kubernetes-external-secrets_patch.yaml
