---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets
  - cert-manager
  - ../../base/postgres
  - ../../base/keycloak

patches:
  # Use CatalogSource from minikube
  - patch: |-
      - op: replace
        path: /spec/source
        value: operatorhubio-catalog
    target:
      kind: Subscription

  - patch: |-
      - op: replace
        path: /spec/sourceNamespace
        value: olm
    target:
      kind: Subscription

  # Patch broken channel (stable is not available in quay.io)
  - patch: |-
      - op: replace
        path: /spec/channel
        value: candidate
    target:
      kind: Subscription
      name: cert-manager
