apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: default-api-server-certificate
  namespace: openshift-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: default-api-server-certificate
    template:
      type: kubernetes.io/tls
  dataFrom:
    - key: openshift-api-server/default-api-server-certificate
