apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: slack-url-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-url-secret
  data:
  - secretKey: slack_api_url
    remoteRef:
      key: stf
      property: SLACK_API_URL
