apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:image-puller
  namespace: postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:keycloak
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:regapp
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:coldfront
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:coldfront-staging
