apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-cluster-admin-0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: vault-operator
  namespace: vault
- kind: ServiceAccount
  name: vault
  namespace: vault
- kind: ServiceAccount
  name: deployer
  namespace: vault
- kind: ServiceAccount
  name: default
  namespace: vault
- kind: ServiceAccount
  name: builder
  namespace: vault
