apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-main
  data:
    - secretKey: alertmanager.yaml
      remoteRef:
        key: nerc-shift-0-monitoring
        property: ALERTMANAGER_YML
