apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: os-ctl-0-pub-iface
spec:
  nodeSelector:
    kubernetes.io/hostname: os-ctl-0
  desiredState:
    interfaces:
    - name: bond0.2142
      type: vlan
      state: up
      ipv4:
        enabled: true
        dhcp: false
        address:
          - ip: 140.247.152.10
            prefix-length: 27
      vlan:
        base-iface: bond0
        id: 2142
