apiVersion: v1
items:
- apiVersion: nmstate.io/v1beta1
  kind: NMState
  metadata:
    name: nmstate
  spec:
    nodeSelector:
      kubernetes.io/arch: amd64
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
