---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mss-route53-credentials
  namespace: cert-manager
spec:
  target:
    name: mss-route53-credentials
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - key: accounts/route53
