apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: default-ingress-certificate
  namespace: openshift-ingress
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: default-ingress-certificate
    template:
      type: kubernetes.io/tls
  dataFrom:
    - key: openshift-ingress/default-ingress-certificate
