---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
        - api.nerc-shift-1.rc.fas.harvard.edu
        servingCertificate:
          name: default-api-server-certificate
