apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: nerc-keycloak
  labels:
    app: sso
  namespace: keycloak
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  externalAccess:
    enabled: true
  extensions:
    - >-
      https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  instances: 2
