apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ctl-0-bond
spec:
  nodeSelector:
    kubernetes.io/hostname: ctl-0
  desiredState:
    interfaces:
    - name: bond0
      type: bond
      state: up
      ipv4:
        enabled: true
        dhcp: true
      link-aggregation:
        mode: balance-rr
        options:
          miimon: '140'
        port:
        - ens5f0
        - ens5f1
      mtu: 9000
