apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: nerc-argocd
  namespace: argocd
spec:
  controller:
    processors: {}
  dex: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  initialSSHKnownHosts: {}
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac: {}
  redis: {}
  repo: {}
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: true
    route:
      enabled: true
    service:
      type: ""
  tls:
    ca: {}
