kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: argocd
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:argocd:nerc-argocd-argocd-server
  - system:serviceaccount:argocd:nerc-argocd-argocd-application-controller
