apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerc-external-secrets
  namespace: external-secrets
spec:
  template:
    spec:
      containers:
        - name: external-secrets
          volumeMounts:
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
              name: vault-tls
              readOnly: true
      volumes:
        - name: vault-tls
          secret:
            secretName: vault-tls
            items:
              - key: ca.crt
                path: ca-certificates.crt
