apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: eck-elastic
  namespace: nerceckdeployment
spec:
  tls:
    termination: passthrough # Elasticsearch is the TLS endpoint
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: eck-elastic-es-http
