apiVersion: v1
kind: Route
metadata:
  name: eck-fleet
  namespace: nerceckdeployment
spec:
  tls:
    termination: passthrough # Kibana is the TLS endpoint
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: eck-fleet-agent-http
