apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck-kibana
  namespace: nerceckdeployment
spec:
  version: 8.6.2
  count: 1
  elasticsearchRef:
    name: "eck-elastic"
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://eck-elastic-nerceckdeployment.apps.aa-dev-shift1.rc.fas.harvard.edu:443","https://eck-elastic-es-http:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://eck-fleet-nerceckdeployment.apps.aa-dev-shift1.rc.fas.harvard.edu:443","https://eck-fleet-agent-http:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        namespace: nerceckdeployment
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: nerceckdeployment
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
