apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: nerc-eck
  namespace: nerc-eck
spec:
  version: 7.17.0
  count: 1
  elasticsearchRef:
    name: nerc-eck
  config:
    server.publicBaseUrl:
      # https://kibana-nerc-eck.apps.nerc-shift-0.rc.fas.harvard.edu
      https://kibana-nerc-eck.apps.aa-shift-dev3.fas.harvard.edu
