apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: crunchy-pgbackrest
  namespace: postgres-operator
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
