apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: crunchy-pgbouncer
  namespace: postgres-operator
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-5'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
