apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: default
    role: alert-rules
  name: prometheus-alarm-rules
  namespace: service-telemetry
spec:
  groups:
    - name: ./openstack.rules
      rules:
        - alert: Collectd metrics receive rate is zero
          expr: rate(sg_total_collectd_msg_received_count[1m]) == 0
        - alert: Ethernet Interface Receive Errors
          expr: increase(collectd_interface_if_errors_rx_total[1h]) > 0
        - alert: Ethernet Interface Transmit Errors
          expr: increase(collectd_interface_if_errors_tx_total[1h]) > 0
