---
# Source: external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nerc-external-secrets
  namespace: "external-secrets"
  labels:
    helm.sh/chart: external-secrets-0.3.6
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: nerc
    app.kubernetes.io/version: "v0.3.6"
    app.kubernetes.io/managed-by: Helm
