apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: nerc-eck
  namespace: nerc-eck
spec:
  version: 7.17.0
  nodeSets:
    - name: default
      count: 10
      config:
        node.store.allow_mmap: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Gi
